services:
    app.form.registration:
        class: Junk\Bundle\GiftBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    app.form.create.event:
        class: Junk\Bundle\GiftBundle\Form\EventType
        calls:
          - [setSecurityContext, [@security.context]]
        tags:
            - { name: form.type, alias: event_type }
    app.form.invite.event:
        class: Junk\Bundle\GiftBundle\Form\InviteType
        tags:
            - { name: form.type, alias: invite_type }
    redirect_register_user.registration.completed:
        class: Junk\Bundle\GiftBundle\EventListener\RegistrationConfirmListener
        arguments: [@router]
        tags:
            - { name: kernel.event_subscriber }
