services:
    app.form.registration:
        class: Junk\Bundle\GiftBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    app.form.create.event:
        class: Junk\Bundle\GiftBundle\Form\EventType
        calls:
          - [setSecurityContext, [@security.context]]
        tags:
            - { name: form.type, alias: event_type }
